#!/bin/bash

term=st

selected=$(echo "Super Mute
Matrix Rain
ASCII Fire" | rofi -dmenu -theme solarized.rasi -p "Select")

if [ "$selected" == "Super Mute" ]; then
	lmc truemute;
	lmc pause;
	pauseallmpv;
	i3-msg workspace 0;
	"$term" -e htop;
elif [ "$selected" == "Matrix Rain" ]; then
	i3-msg workspace 0
	exec "$term" -e unimatrix -b -s 95 -l o
elif [ "$selected" == "ASCII Fire" ]; then
	i3-msg workspace 0
	exec "$term" -e cacafire
else
	exit
fi
