#!/bin/bash

SCRIPT_FOLDER="$HOME/Code/ArchConfigs/scripts"
SCRIPT_FILE="$SCRIPT_FOLDER/$1"

if [[ -f $SCRIPT_FILE ]]; then
  vim $SCRIPT_FILE
else
  echo '#!/bin/bash' > $SCRIPT_FILE
  chmod u+x $SCRIPT_FILE
  ln -sf $SCRIPT_FILE ~/.local/bin/$1
  vim $SCRIPT_FILE
fi
