#!/bin/bash

while true; do
	battery_level="$(acpi -b | grep -v "Charging" | grep -P -o '[0-9]+(?=%)')"
	charging="$(acpi -a | cut -d' ' -f3 | cut -d- -f1)"

	if [[ $charging = "off" ]]; then
    		if [ $battery_level -lt 10 ]; then
			notify-send -u critical "             
   BATTERY LOW: ${battery_level}%   
              " -t 0
    		elif [ $battery_level -lt 20 ]; then
			notify-send -u normal "Battery Low: ${battery_level}%" -t 0
    		fi
	fi
    	sleep 150 #150 seconds
done
